# -*- coding: utf-8 -*-
"""Blood Cell Detection using YOLO11

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10X6ABYrsAr3ChWnszr0g-2ivoZdrYArb
"""

# YOLOv8 kurulumu
# ----------------------------------------
!pip install ultralytics==8.1.0
from ultralytics import YOLO
import os

# Kaggle API yükleme
# ----------------------------------------
from google.colab import files
files.upload()

# Kaggle API'yi etkinleştirme
# ----------------------------------------
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

# BCCD datasetini indirme
# ----------------------------------------
!kaggle datasets download -d orvile/bccd-blood-cell-count-and-detection-dataset
!unzip -o bccd-blood-cell-count-and-detection-dataset.zip -d BCCD

import xml.etree.ElementTree as ET
import os

classes = ["RBC", "WBC", "Platelets"]

img_dir = "BCCD/BCCD/JPEGImages"
ann_dir = "BCCD/BCCD/Annotations"
yolo_dir = "BCCD/labels"

os.makedirs(yolo_dir, exist_ok=True)

!ls -R BCCD

import os

# YOLO label klasörleri
os.makedirs("labels/train", exist_ok=True)
os.makedirs("labels/val", exist_ok=True)
os.makedirs("labels/test", exist_ok=True)

print("Klasörler hazır ✔")

import json

classes = ["RBC", "WBC", "Platelets"]

def convert(json_file, output_dir):
    with open(json_file, "r") as f:
        data = json.load(f)

    img_w = data["width"]
    img_h = data["height"]

    out_path = os.path.join(output_dir, os.path.basename(json_file).replace(".json", ".txt"))

    with open(out_path, "w") as lab:
        for obj in data["objects"]:
            cls = obj["label"]
            if cls not in classes:
                continue

            cls_id = classes.index(cls)

            xmin = obj["bbox"]["xmin"]
            ymin = obj["bbox"]["ymin"]
            xmax = obj["bbox"]["xmax"]
            ymax = obj["bbox"]["ymax"]

            # YOLO format (normalized)
            x = (xmin + xmax) / 2 / img_w
            y = (ymin + ymax) / 2 / img_h
            w = (xmax - xmin) / img_w
            h = (ymax - ymin) / img_h

            lab.write(f"{cls_id} {x} {y} {w} {h}\n")


print("JSON → YOLO fonksiyonu hazır ✔")

import os

os.makedirs("labels/train", exist_ok=True)
os.makedirs("labels/val", exist_ok=True)
os.makedirs("labels/test", exist_ok=True)

print("Label klasörleri hazır ✔")

import json
import os

classes = ["RBC", "WBC", "Platelets"]

def convert(json_file, output_dir):
    with open(json_file, "r") as f:
        data = json.load(f)

    # Görüntü boyutu
    img_w = data["size"]["width"]
    img_h = data["size"]["height"]

    out_path = os.path.join(output_dir, os.path.basename(json_file).replace(".json", ".txt"))

    with open(out_path, "w") as txt:
        for obj in data["objects"]:

            cls = obj["classTitle"]
            if cls not in classes:
                continue

            cls_id = classes.index(cls)

            # BBOX
            xmin = obj["points"]["exterior"][0][0]
            ymin = obj["points"]["exterior"][0][1]
            xmax = obj["points"]["exterior"][1][0]
            ymax = obj["points"]["exterior"][1][1]

            # YOLO format (normalize)
            x = (xmin + xmax) / 2 / img_w
            y = (ymin + ymax) / 2 / img_h
            w = (xmax - xmin) / img_w
            h = (ymax - ymin) / img_h

            txt.write(f"{cls_id} {x} {y} {w} {h}\n")

print("JSON → YOLO fonksiyonu hazır ✔")

import os
print(os.listdir())

!ls -R BCCD

!ls -R

!kaggle datasets download -d orvile/bccd-blood-cell-count-and-detection-dataset -o

!unzip -o bccd-blood-cell-count-and-detection-dataset.zip -d BCCD

!ls -R BCCD

import os, json

# Sınıflar
classes = ["RBC", "WBC", "Platelets"]

# YOLO output klasörleri
os.makedirs("dataset/images/train", exist_ok=True)
os.makedirs("dataset/images/val", exist_ok=True)
os.makedirs("dataset/images/test", exist_ok=True)

os.makedirs("dataset/labels/train", exist_ok=True)
os.makedirs("dataset/labels/val", exist_ok=True)
os.makedirs("dataset/labels/test", exist_ok=True)


def convert_json_to_yolo(json_path, save_path):
    """DatasetNinja JSON → YOLO TXT dönüştürücü"""

    with open(json_path, "r") as f:
        data = json.load(f)

    img_w = data["size"]["width"]
    img_h = data["size"]["height"]

    with open(save_path, "w") as out:
        for obj in data["objects"]:

            cls = obj["classTitle"]
            if cls not in classes:
                continue

            cls_id = classes.index(cls)

            xmin = obj["points"]["exterior"][0][0]
            ymin = obj["points"]["exterior"][0][1]
            xmax = obj["points"]["exterior"][1][0]
            ymax = obj["points"]["exterior"][1][1]

            # YOLO normalize format
            x = (xmin + xmax) / 2 / img_w
            y = (ymin + ymax) / 2 / img_h
            w = (xmax - xmin) / img_w
            h = (ymax - ymin) / img_h

            out.write(f"{cls_id} {x} {y} {w} {h}\n")

print("JSON → YOLO fonksiyonu hazır ✔")

import shutil

def process_split(split):
    img_dir = f"BCCD/{split}/img"
    ann_dir = f"BCCD/{split}/ann"

    out_img = f"dataset/images/{split}"
    out_lab = f"dataset/labels/{split}"

    count = 0

    for ann_file in os.listdir(ann_dir):
        if not ann_file.endswith(".json"):
            continue

        ann_path = os.path.join(ann_dir, ann_file)
        img_name = ann_file.replace(".json", "")
        img_path = os.path.join(img_dir, img_name)

        # Etiket oluştur
        label_save_path = os.path.join(out_lab, ann_file.replace(".json", ".txt"))
        convert_json_to_yolo(ann_path, label_save_path)

        # Görüntüyü kopyala
        shutil.copy(img_path, os.path.join(out_img, img_name))

        count += 1

    print(f"{split.upper()} set oluşturuldu ✔ {count} adet örnek")


# ÇALIŞTIR
process_split("train")
process_split("val")
process_split("test")

yaml_content = """
path: dataset

train: images/train
val: images/val
test: images/test

names:
  0: RBC
  1: WBC
  2: Platelets
"""

with open("dataset.yaml", "w") as f:
    f.write(yaml_content)

print("dataset.yaml hazır ✔")

from ultralytics import YOLO

# PRETRAINED OLMAYAN YOLOV8n MODELİ
model = YOLO("yolov8n.yaml")

print("Model hazır ✔")

!mkdir -p /content/datasets
!mv dataset /content/datasets/

!ls /content/datasets

!mv dataset.yaml /content/datasets/

!pip install -U ultralytics

from ultralytics import YOLO

model = YOLO("yolo11n.yaml")  # YOLO11 nano modeli

import os

label_path = "/content/datasets/dataset/labels/train"

print("📁 Kontrol edilen klasör:", label_path)
print("-" * 50)

empty_files = []
wrong_format_files = []
correct_files = []

for file in os.listdir(label_path):
    if file.endswith(".txt"):
        full = os.path.join(label_path, file)
        content = open(full, "r").read().strip()

        # Dosya boş mu?
        if len(content) == 0:
            empty_files.append(file)
            continue

        # Satırları kontrol et
        valid = True
        for line in content.splitlines():
            parts = line.split()
            if len(parts) != 5:
                valid = False
                break
            try:
                cls = int(parts[0])
                nums = list(map(float, parts[1:]))
                if not all(0 <= n <= 1 for n in nums):
                    valid = False
                    break
            except:
                valid = False
                break

        if valid:
            correct_files.append(file)
        else:
            wrong_format_files.append(file)

print("\n📌 BOŞ LABEL DOSYALARI:", len(empty_files))
print(empty_files[:10])

print("\n⚠️ YANLIŞ FORMAT LABEL DOSYALARI:", len(wrong_format_files))
print(wrong_format_files[:10])

print("\n✅ DOĞRU FORMATTA LABEL DOSYALARI:", len(correct_files))
print(correct_files[:10])

import os
train_img = "/content/datasets/dataset/images/train"
print(sorted(os.listdir(train_img))[:30])
print("Toplam:", len(os.listdir(train_img)))

import os
train_lbl = "/content/datasets/dataset/labels/train"
print(sorted(os.listdir(train_lbl))[:30])
print("Toplam:", len(os.listdir(train_lbl)))

import os

label_dir = "/content/datasets/dataset/labels/train"

for f in os.listdir(label_dir):
    if f.endswith(".jpeg.txt"):
        old = os.path.join(label_dir, f)
        new = os.path.join(label_dir, f.replace(".jpeg.txt", ".txt"))
        os.rename(old, new)

print("✔ Label isimleri düzeltildi!")
print(os.listdir(label_dir)[:20])

label_dir = "/content/datasets/dataset/labels/val"

for f in os.listdir(label_dir):
    if f.endswith(".jpeg.txt"):
        old = os.path.join(label_dir, f)
        new = os.path.join(label_dir, f.replace(".jpeg.txt", ".txt"))
        os.rename(old, new)

print("✔ Val label isimleri düzeltildi!")
print(os.listdir(label_dir)[:20])

!rm -f /content/datasets/dataset/labels/train.cache
!rm -f /content/datasets/dataset/labels/val.cache

print("✔ Cache temizlendi!")

from ultralytics import YOLO

model = YOLO("yolo11n.pt")

model.train(
    data="/content/datasets/dataset.yaml",
    epochs=50,
    imgsz=640,
    batch=16,
    name="train_yolo11_fixed",
    workers=4
)

from google.colab import files
uploaded = files.upload()

import os

model_path = "/content/runs/detect/train_yolo11_fixed/weights"
print("📌 Model klasörü:", model_path)
print("📄 Klasördeki dosyalar:")
print(os.listdir(model_path))

!zip -r runs.zip /content/runs

from google.colab import files
files.download("runs.zip")

import os

for root, dirs, files in os.walk("/content/runs", topdown=True):
    level = root.replace("/content/runs", "").count(os.sep)
    indent = " " * 2 * level
    print(f"{indent}{os.path.basename(root)}/")
    subindent = " " * 2 * (level + 1)
    for f in files:
        print(f"{subindent}{f}")